name: "Hello world workflow"

# Controls when the action will run. Triggers the workflow on push some to main or production branch
on:
   push:
      branches:
       -main
       -Production

jobs:
   hello_word:
      runs-on: ubuntu-latest
      steps:
         - name: "Print hello world"
           run: echo "Hello world"
